# Generated by Django 4.1.2 on 2022-10-11 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_location_page"),
    ]

    operations = [
        migrations.AlterModelTable(name="location", table="ABCDE",),
    ]
